# Generated by Django 4.0.5 on 2022-08-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomToken",
        ),
    ]
