# Generated by Django 4.0.5 on 2022-08-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_delete_customtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.faculty"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="group",
            field=models.ForeignKey(
                error_messages={
                    "unique": "Группа с таким именем уже зарегистрирована."
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="users.group",
                unique=True,
            ),
        ),
    ]
