# Generated by Django 4.0.5 on 2022-08-16 15:48

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_customuser_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="group",
            field=models.CharField(
                error_messages={
                    "unique": "Группа с таким именем уже зарегистрирована."
                },
                max_length=10,
                unique=True,
                validators=[users.validators.UnicodeGroupValidator()],
            ),
        ),
    ]
