# Generated by Django 4.0.5 on 2022-08-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="group",
            field=models.OneToOneField(
                error_messages={"unique": "Группа с таким именем уже зарегистрирована"},
                on_delete=django.db.models.deletion.CASCADE,
                to="users.group",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
