# Generated by Django 4.0.5 on 2022-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_customuser_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="faculty",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="group",
            field=models.CharField(
                error_messages={"unique": "Группа с таким именем уже существует."},
                max_length=15,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Faculty",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
