# Generated by Django 4.0.5 on 2022-09-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_telegramuser_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupusertelegram",
            name="token",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
