# Generated by Django 4.0.5 on 2022-09-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_telegramuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
