# Generated by Django 4.0.5 on 2022-10-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_groupusertelegram_owner_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[("PTY", "PairsToday"), ("PTW", "PairsTomorrow")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="notification_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
