# Generated by Django 4.0.5 on 2022-11-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_alter_telegramuser_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="notification_time_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
