# Generated by Django 4.0.5 on 2023-01-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_telegramuser_notification_time_min"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupUserTelegram",
        ),
    ]
