# Generated by Django 4.0.5 on 2023-01-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_alter_telegramuser_token_telegramusertoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="notification_time",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="notification_time_min",
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="action",
            field=models.CharField(
                choices=[
                    ("PTY", "PairsToday"),
                    ("PTW", "PairsTomorrow"),
                    ("NONE", "none"),
                ],
                default="NONE",
                max_length=4,
            ),
        ),
    ]
