# Generated by Django 4.0.5 on 2023-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_remove_telegramuser_notification_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="notification_time",
            field=models.TimeField(null=True),
        ),
    ]
