# Generated by Django 4.0.5 on 2023-01-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_telegramuser_notification_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="notification_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
