version: '3'

x-common-variables: &common-variables
    ALLOWED_HOSTS: "*"
    DEBUG: "True"
    POSTGRES_DB: postgres
    POSTGRES_HOST: db
    POSTGRES_NAME: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    SECRET_KEY: django-insecure-b(=r+o15ecqk0yslac@*^@w^5a8#v8$u^^j#9p56slz*!o5gnk

services:
  web:
    build:
      context: .
      args:
        - DEV=true
    restart: unless-stopped
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    environment: *common-variables
    volumes:
      - ./HoraroBackend/media:/app/media/
      - .:/app/

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
       - staging_postgres_data:/var/lib/postgresql/data
       - ./dump:/dump:ro
    environment: *common-variables
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    hostname: redis
    depends_on:
      - web

  worker:
    build:
      context: .
    restart: unless-stopped
    hostname: worker
    entrypoint: celery
    command: -A config.celery.app worker --beat --loglevel=debug
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis
      - db
    environment: *common-variables

  flower:
    build:
      context: .
    restart: unless-stopped
    hostname: flower
    entrypoint: celery
    command: -A config.celery.app flower
    volumes:
      - ./:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
    environment: *common-variables

volumes:
  staging_postgres_data: