# Generated by Django 4.0.5 on 2022-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
