# Generated by Django 4.0.5 on 2022-07-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_blockuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
    ]
