# Generated by Django 4.0.5 on 2022-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_numberweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockuser",
            name="username",
            field=models.TextField(default=""),
        ),
    ]
