# Generated by Django 4.0.5 on 2022-08-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0009_userprofile_moderator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockUser",
        ),
    ]
