# Generated by Django 4.0.5 on 2022-08-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_delete_blockuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
