# Generated by Django 4.0.5 on 2022-08-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0012_day_type_week_schedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedules",
        ),
    ]
