# Generated by Django 4.0.5 on 2022-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0013_delete_schedules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="number_pair",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
