# Generated by Django 4.0.5 on 2022-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0014_alter_schedule_number_pair"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("is_main", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
