# Generated by Django 4.0.5 on 2022-10-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0015_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
