# Generated by Django 4.0.5 on 2022-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0016_event_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
